rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/python/estimator/model_fn.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/python/client/session.pyc 
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/local/lib/python2.7/site-packages/tensorflow/python/estimator/model_fn.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/contrib/opt/python/training/lazy_adam_optimizer.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/contrib/optimizer_v2/adam.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/contrib/optimizer_v2/optimizer_v2.pyc
rm -f /opt/virtualenv-for-tensorflow-1.8/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc
rm -f /root/ssy/tensor2tensor-1.6.3/tensor2tensor/models/research/transformer_moe.pyc
